### ISSUE TITLE
error when i try to build 

### ISSUE THREAD

**Issue by fferraro87** [mickael-kerjean/integrapptor#1]
hi,
i'm using manjaro linux and i've npm 5.2.0 installed.

when i do npm run build i've this error : 

```
> Integrapptor@1.0.0 build /home/francesco/integrapptor-master
> node generate.js

module.js:591
    throw err;
    ^

SyntaxError: /home/francesco/integrapptor-master/config.json: Unexpected token ] in JSON at position 351
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/francesco/integrapptor-master/generate.js:2:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Integrapptor@1.0.0 build: `node generate.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Integrapptor@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

do you know where i'm wrong?

**Comment by fferraro87** [comment]
Ok i've found error on config.json but now i've another one.
when i do npm run package-linux

i've this error : 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'package-linux' ]
2 info using npm@5.2.0
3 info using node@v8.1.3
4 verbose run-script [ 'prepackage-linux', 'package-linux', 'postpackage-linux' ]
5 info lifecycle Integrapptor@1.0.0~prepackage-linux: Integrapptor@1.0.0
6 info lifecycle Integrapptor@1.0.0~package-linux: Integrapptor@1.0.0
7 verbose lifecycle Integrapptor@1.0.0~package-linux: unsafe-perm in lifecycle true
8 verbose lifecycle Integrapptor@1.0.0~package-linux: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/francesco/integrapptor-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle Integrapptor@1.0.0~package-linux: CWD: /home/francesco/integrapptor-master
10 silly lifecycle Integrapptor@1.0.0~package-linux: Args: [ '-c',
10 silly lifecycle   'electron-packager . --overwrite --platform=linux --arch=x64 --icon=src/assets/icons/512x512.png --prune=true --out=release-builds' ]
11 silly lifecycle Integrapptor@1.0.0~package-linux: Returned: code: 1  signal: null
12 info lifecycle Integrapptor@1.0.0~package-linux: Failed to exec package-linux script
13 verbose stack Error: Integrapptor@1.0.0 package-linux: `electron-packager . --overwrite --platform=linux --arch=x64 --icon=src/assets/icons/512x512.png --prune=true --out=release-builds`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:897:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid Integrapptor@1.0.0
15 verbose cwd /home/francesco/integrapptor-master
16 verbose Linux 4.4.71-1-MANJARO
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "package-linux"
18 verbose node v8.1.3
19 verbose npm  v5.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error Integrapptor@1.0.0 package-linux: `electron-packager . --overwrite --platform=linux --arch=x64 --icon=src/assets/icons/512x512.png --prune=true --out=release-builds`
22 error Exit status 1
23 error Failed at the Integrapptor@1.0.0 package-linux script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

how can i fix this?

**Comment by mickael-kerjean** [comment]
First issues was coming from a syntax error in your config.json.

Hum I can't replicate your issue even with the same node version as you.
Can you try:
```
rm -rf node_modules
npm install
npm run build
node node_modules/.bin/electron-packager . --overwrite --platform=linux --arch=x64 --icon=src/assets/icons/512x512.png --prune=true --out=release-builds
```
And send back the error if you still have it?

**Comment by fferraro87** [comment]
ok now it works.

but i've many error when i try to build for windows os like this : 
```
> Integrapptor@1.0.0 package-win /home/fferraro/Projects/integrapptor-master
> electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=src/assets/icons/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="Electron Tutorial App"

Packaging app for platform win32 ia32 using electron v1.6.11
ENAMETOOLONG: name too long, unlink '/home/fferraro/Projects/integrapptor-master/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/node_modules/currently-unhandled/browser.js'

npm ERR! Linux 4.8.6-300.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "package-win"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Integrapptor@1.0.0 package-win: `electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=src/assets/icons/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="Electron Tutorial App"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Integrapptor@1.0.0 package-win script 'electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=src/assets/icons/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="Electron Tutorial App"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Integrapptor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=src/assets/icons/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="Electron Tutorial App"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Integrapptor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Integrapptor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fferraro/Projects/integrapptor-master/npm-debug.log
```
why?

**Comment by mickael-kerjean** [comment]
For windows, can you try:
1) delete the release-builds folder and the node_modules folder
2) open up a cmd prompt:
```
npm install
npm run build
.\node_modules\.bin\electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=src/assets/icons/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="Integrapptor"
```

To help me replicate your error, can you provide the exact steps you went into to generate this? 
Did you do a `npm install` before launching `npm run package-linux` or `npm run package-win`?

**Comment by fferraro87** [comment]
hi, thanks for your help.

yes i do `npm install` before launching `npm run package-win` but i've that error before. (i'm doing this on linux OS ) 
With your command after that filled /tmp folder with 6,4G and after few minutes, it returns this error : 
```
ENAMETOOLONG: name too long, unlink '/tmp/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/electron-packager/win32-ia32/Integrapptor-win32-ia32/resources/app/node_modules/electron-osx-sign/default.entitlements.darwin.inherit.plist'
```

**Comment by mickael-kerjean** [comment]
Oh I think I understand now.  I'm not sure you can create the exe from linux. That would be amazing to make this work. I'll make a few tests on a linux machine and see how it goes. 

Maybe if you give me your config.json, I can create the exe and send it back to you.

> thanks for your help.

To be fair, you made me realise the documentation needs improvements. Thank you for opening it!

**Comment by fferraro87** [comment]
ah ok thanks, i've thought that i can build every package only from linux.
I've try to build win package on windows and now it works fine.

Thanks
